### ISSUE TITLE
tf2.attributes.txt not loading correctly

### ISSUE THREAD

**Issue by wilfurdmcwargnash** [FlaminSarge/tf2attributes#18] opened 2017-12-27 21:47 UTC
``L 12/27/2017 - 13:21:19: [SM] Error parsing gameconfig file`` ``"c:\allcrits\tf2\tf\addons\sourcemod\gamedata\tf2.attributes.txt":``
``L 12/27/2017 - 13:21:19: [SM] Error 1 on line 0, col 0: Stream failed to open``
``L 12/27/2017 - 13:21:19: [SM] Exception reported: Unable to open tf2.attributes: File could not be`` ``opened: The system cannot find the file specified.``

``L 12/27/2017 - 13:21:19: [SM] Blaming: tf2attributes.smx``
``L 12/27/2017 - 13:21:19: [SM] Call stack trace:``
``L 12/27/2017 - 13:21:19: [SM]   [0] LoadGameConfigFile``
``L 12/27/2017 - 13:21:19: [SM]   [1] Line 85, C:\sourcemod\tf2attributes\tf2attributes.sp::OnPluginStart``
``L 12/27/2017 - 13:21:19: [SM] Unable to load plugin "tf2attributes.smx": Error detected in plugin`` ``startup(see error logs)``

``]sm plugins load tf2attributes``
``[SM] Plugin tf2attributes.smx is already loaded.``

**Comment by FlaminSarge** [comment] 2017-12-29 07:19
It's looking for a file. Does that file exist on your server?

**Comment by wilfurdmcwargnash** [comment] 2017-12-30 02:44
yes

**Comment by FlaminSarge** [comment] 2018-02-09 09:23
Duplicate of #12

**Closed by FlaminSarge** 2018-02-09 09:23 UTC
