### ISSUE TITLE
Unable to load plugin "tf2attributes.smx" tf2attributes.sp::OnPluginStart

### ISSUE THREAD

**Issue by tarantazzz** [FlaminSarge/tf2attributes#19] opened 2018-02-06 12:23 UTC
L 02/06/2018 - 15:15:57: [SM] Exception reported: Could not initialize call to CAttributeList::SetRuntimeAttributeValue
L 02/06/2018 - 15:15:57: [SM] Blaming: tf2attributes.smx
L 02/06/2018 - 15:15:57: [SM] Call stack trace:
L 02/06/2018 - 15:15:57: [SM]   [0] SetFailState
L 02/06/2018 - 15:15:57: [SM]   [1] Line 176, C:\sourcemod\tf2attributes\tf2attributes.sp::OnPluginStart
L 02/06/2018 - 15:15:57: [SM] Unable to load plugin "tf2attributes.smx": Error detected in plugin startup (see error logs)

AAAAAAAAAAAAAWAWWWWWWWWWWW

**Comment by FlaminSarge** [comment] 2018-02-07 04:41
You're gonna need to provide more information than that.

**Comment by FlaminSarge** [comment] 2018-02-09 09:23
Duplicate of #12

**Closed by FlaminSarge** 2018-02-09 09:23 UTC
