### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by SuperzScoutz** [FlaminSarge/tf2attributes#22] opened 2018-02-09 05:31 UTC
I installed the latest to fix my other problem but then this happended

`L 02/08/2018 - 22:27:13: SourceMod error session started

L 02/08/2018 - 22:27:13: Info (map "vsh_2fortdesk_v8") (file "errors_20180208.log")

L 02/08/2018 - 22:27:13: [SM] Exception reported: Could not initialize call to CEconItemSchema::GetAttributeDefinition

L 02/08/2018 - 22:27:13: [SM] Blaming: tf2attributes.smx
L 02/08/2018 - 22:27:13: [SM] Call stack trace:
L 02/08/2018 - 22:27:13: [SM]   [0] SetFailState
L 02/08/2018 - 22:27:13: [SM]   [1] Line 142, C:\sourcemod\tf2attributes\tf2attributes.sp::OnPluginStart
L 02/08/2018 - 22:27:13: [SM] Unable to load plugin "tf2attributes.smx": Error detected in plugin startup (see error logs)
`

**Comment by FlaminSarge** [comment] 2018-02-09 09:22
Duplicate of #12

**Closed by FlaminSarge** 2018-02-09 09:22 UTC
